# [\#10713 Issue](https://github.com/ethereum/solidity/issues/10713) `closed`: [Testing] Seg fault probably due to boost::filesystem
**Labels**: `bug :bug:`, `testing :hammer:`


#### <img src="https://avatars.githubusercontent.com/u/2388185?v=4" width="50">[bshastry](https://github.com/bshastry) opened issue at [2021-01-04 14:26](https://github.com/ethereum/solidity/issues/10713):

<!--## Prerequisites

- First, many thanks for taking part in the community. We really appreciate that.
- We realize there is a lot of information requested here. We ask only that you do your best to provide as much information as possible so we can better help you.
- Support questions are better asked in one of the following locations:
	- [Solidity chat](https://gitter.im/ethereum/solidity)
	- [Stack Overflow](https://ethereum.stackexchange.com/)
- Ensure the issue isn't already reported.
- The issue should be reproducible with the latest solidity version; however, this isn't a hard requirement and being reproducible with an older version is sufficient.
-->

## Description

```
==== Source://// ====
import ".";
```

throws

https://github.com/boostorg/filesystem/blob/6b5e38134a336b6ea777cd8a69b6ae929819db7e/src/path.cpp#L223

via

https://github.com/ethereum/solidity/blob/fdbb4d9a8fef8623eca99a807675815f3c0ebce4/libsolutil/CommonIO.cpp#L140

## Environment

- Compiler version: latest develop

## Steps to Reproduce

- Create a test file called `invalid_filename.sol` in `test/libsolidity/syntaxTests/`
- Do

```
$ isoltest -t syntaxTests/test
syntaxTests/invalid_filename.sol: Exception during test: basic_string::erase: __pos (which is 18446744073709551615) > this->size() (which is 4)
(e)dit/(s)kip/(q)uit? 
```




-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2022.05.23 at 03:51:38.]
