# [\#2155 PR](https://github.com/ethereum/solidity/pull/2155) `merged`: Guard ReadFileCallback exceptions

#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) opened issue at [2017-04-21 13:46](https://github.com/ethereum/solidity/pull/2155):

Do not allow `ReadFileCallback` to bubble exceptions. It should return the error message properly instead.

#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2017-04-21 15:16](https://github.com/ethereum/solidity/pull/2155#issuecomment-296219536):

Without this, for example in the StandardCompiler if I try to import an invalid file this is masked via:
```
{"errors":[{"component":"general","formattedMessage":"Internal exception in StandardCompiler::compilerInternal","message":"Internal exception in StandardCompiler::compilerInternal","severity":"error","type":"InternalCompilerError"}]}
```

Internally this is the bug:
```
libc++abi.dylib: terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::canonical: No such file or directory: "/Users/alex/Projects/solidity/build/file://test"
```

#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2017-04-24 10:25](https://github.com/ethereum/solidity/pull/2155#issuecomment-296609110):

@chriseth ready to merge?


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
