# [\#3028 Issue](https://github.com/ethereum/solidity/issues/3028) `closed`: Shall block.blockhash throw if the argument is invalid?
**Labels**: `breaking change :warning:`, `language design :rage4:`, `closed due inactivity`, `stale`


#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) opened issue at [2017-10-05 09:34](https://github.com/ethereum/solidity/issues/3028):



#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2017-10-05 10:00](https://github.com/ethereum/solidity/issues/3028#issuecomment-334419025):

Invalid as in out of range?

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2017-10-05 10:07](https://github.com/ethereum/solidity/issues/3028#issuecomment-334420667):

Yes

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2017-10-05 10:07](https://github.com/ethereum/solidity/issues/3028#issuecomment-334420783):

We could also just throw if it returns zero, in anticipation for potential changes in the EVM.

#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2017-10-05 10:52](https://github.com/ethereum/solidity/issues/3028#issuecomment-334430274):

The opcode is defined as returning 0 in case of out of range. The new blockhash will have weird rules to see if the hash is present or not - how will the user be able to check if it is in range without throwing?

#### <img src="https://avatars.githubusercontent.com/u/138426?u=3117125771b06e3aa8da468c8f41e4038d717974&v=4" width="50">[federicobond](https://github.com/federicobond) commented at [2017-10-06 21:34](https://github.com/ethereum/solidity/issues/3028#issuecomment-334875758):

Agree with @axic that it will be hard to check beforehand if the value is present. This could be partially solved with the planned try-catch construct, but even then you are not forced or even encouraged to handle the failure case in your code. 

Another, more explicit alternative is returning a `(uint256 hash, bool exists)` tuple.

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2017-10-06 23:44](https://github.com/ethereum/solidity/issues/3028#issuecomment-334894089):

So a better option would be to have the SMT checker see if the argument is in range?

#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2019-12-13 11:29](https://github.com/ethereum/solidity/issues/3028#issuecomment-565408308):

Could reconsider this now with having `try/catch` in place.

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2019-12-16 10:38](https://github.com/ethereum/solidity/issues/3028#issuecomment-566004341):

For that, we need to extend try/catch to certain non-external functions and I don't know if this would be a good idea.

#### <img src="https://avatars.githubusercontent.com/in/15368?v=4" width="50">[github-actions](https://github.com/apps/github-actions) commented at [2023-01-27 12:05](https://github.com/ethereum/solidity/issues/3028#issuecomment-1406406644):

Hi everyone! This issue has been closed due to inactivity.
If you think this issue is still relevant in the latest Solidity version and you have something to [contribute](https://docs.soliditylang.org/en/latest/contributing.html), feel free to reopen.
However, unless the issue is a concrete proposal that can be implemented, we recommend starting a language discussion on the [forum](https://forum.soliditylang.org) instead.


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
