# [\#4458 Issue](https://github.com/ethereum/solidity/issues/4458) `closed`: Fuzzer catches too many exceptions
**Labels**: `bug :bug:`


#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) opened issue at [2018-07-09 10:35](https://github.com/ethereum/solidity/issues/4458):

The fuzzer currently does not fail on failing assertions.

Example code (from #4417):
```
pragma solidity ^0.4.24;

contract SomeContract {

  uint public balance = 0;


  function balance(uint number) public {

  }

  function doSomething() public {
    balance(3);
  }
}
```

-- found by @mattaereal 

#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2018-07-09 22:16](https://github.com/ethereum/solidity/issues/4458#issuecomment-403637858):

I think this was broken by #2213, which means for a year.

For the above example, the error returned is `InternalCompilerError: Requested type not present.`, while the fuzzer is grepping for the text `Internal compiler error`.


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
