# [\#7378 Issue](https://github.com/ethereum/solidity/issues/7378) `closed`: ICE pop a dynamic storage array of mapping
**Labels**: `bug :bug:`


#### <img src="https://avatars.githubusercontent.com/u/504195?u=ce2facd14af9fd474ebff49f0d44891f56f7500f&v=4" width="50">[leonardoalt](https://github.com/leonardoalt) opened issue at [2019-09-08 20:04](https://github.com/ethereum/solidity/issues/7378):

```
contract C {
    mapping (uint => uint)[] a;
    function f() public {
        a.pop();
    }
}
```

```
libsolidity/codegen/LValue.cpp(401): Throw in function virtual void dev::solidity::StorageItem::setToZero(const langutil::SourceLocation&, bool) const
Dynamic exception type: boost::wrapexcept<langutil::InternalCompilerError>
std::exception::what: Clearing of unsupported type requested: mapping(uint256 => uint256)
[dev::tag_comment*] = Clearing of unsupported type requested: mapping(uint256 => uint256)
```

Deleting a `mapping` gives a `TypeError`, which is correct.
Here the `pop` tries to `setToZero` the last mapping which is then caught by codegen.
`a.pop()` should be valid, since popping the array should be fine. But because of the base type being a `mapping` it shouldn't try to `setToZero`.

#### <img src="https://avatars.githubusercontent.com/u/504195?u=ce2facd14af9fd474ebff49f0d44891f56f7500f&v=4" width="50">[leonardoalt](https://github.com/leonardoalt) commented at [2019-09-08 20:25](https://github.com/ethereum/solidity/issues/7378#issuecomment-529238442):

```
    function g() public returns (uint) {
        delete a;
    }
```
This works.
I haven't looked into the code, but my guess is that `pop` is somehow calling `setToZero` without checking the base type. Maybe `pop` calling `delete` internally would work?


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
