# [\#7337 PR](https://github.com/ethereum/solidity/pull/7337) `merged`: Try to fix appveyor run by chaning bytecode pull output from stderr to stdout.

#### <img src="https://avatars.githubusercontent.com/u/1347491?v=4" width="50">[ekpyron](https://github.com/ekpyron) opened issue at [2019-09-04 09:01](https://github.com/ethereum/solidity/pull/7337):

Should fix errors like https://ci.appveyor.com/project/ethereum-free/solidity/builds/27151440

github.com resolves to a whole range of changing IP addresses - I think the warning occurs, if the IP address changes between the clone and the pull in the script. And any output to stderr seems to be considered an error.

The line itself was only added to fix the tests, so it should be safe to ignore warnings (and errors for that matter) in it, right? The really relevant thing is the return code of the git push?

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2019-09-04 10:41](https://github.com/ethereum/solidity/pull/7337#issuecomment-527846139):

Just as a note: appveyor fails if there is anything on stderr.


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
