# [\#10553 Issue](https://github.com/ethereum/solidity/issues/10553) `closed`: Compiler crash (not ICE): Unknown exception during compilation: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0) ```

#### <img src="https://avatars.githubusercontent.com/u/967816?u=e15de0869a62036529220016b1729fa1a6c18b5b&v=4" width="50">[agroce](https://github.com/agroce) opened issue at [2020-12-09 17:15](https://github.com/ethereum/solidity/issues/10553):

## Description

This contract:
```solidity
interface ERC165 {
    /// @return `true` if the contract implements `interfaceID` and
    function supportsInterface(bytes4 interfaceID) external view returns (bool);
}
abstract contract ERC165MappingImplementation is ERC165 {
    function supportsInterface(bytes4 interfaceID) external view  {    }
}
interface Simpson {}
contract Lisa is ERC165MappingImplementation, Simpson {
}
```

produces:

```
Unknown exception during compilation: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.6-develop.2020.12.9+commit.052b97e2.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.


#### <img src="https://avatars.githubusercontent.com/u/967816?u=e15de0869a62036529220016b1729fa1a6c18b5b&v=4" width="50">[agroce](https://github.com/agroce) commented at [2020-12-09 17:23](https://github.com/ethereum/solidity/issues/10553#issuecomment-741920451):

Confirmed this is not whatever is going on in #10532 -- on mac OS fresh checkout and build this contract produces:

```
Unknown exception during compilation: vector
```

#### <img src="https://avatars.githubusercontent.com/u/504195?u=ce2facd14af9fd474ebff49f0d44891f56f7500f&v=4" width="50">[leonardoalt](https://github.com/leonardoalt) commented at [2020-12-09 17:29](https://github.com/ethereum/solidity/issues/10553#issuecomment-741924489):

I can confirm this one:
```
(gdb) bt
#0  0x00007ffff6e53072 in __cxxabiv1::__cxa_throw (obj=obj@entry=0x55555646bc40, tinfo=0x7ffff6f7f268 <typeinfo for std::out_of_range>, 
    dest=0x7ffff6e68fa0 <std::out_of_range::~out_of_range()>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:78
#1  0x00007ffff6e495ed in std::__throw_out_of_range_fmt (__fmt=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/functexcept.cc:82
#2  0x00005555557405d6 in std::vector<std::shared_ptr<solidity::frontend::VariableDeclaration>, std::allocator<std::shared_ptr<solidity::frontend::VariableDeclaration> > >::_M_range_check (
    this=0x55555645c620, __n=0) at /usr/include/c++/10.2.0/bits/stl_vector.h:1073
#3  0x0000555555740169 in std::vector<std::shared_ptr<solidity::frontend::VariableDeclaration>, std::allocator<std::shared_ptr<solidity::frontend::VariableDeclaration> > >::at (
    this=0x55555645c620, __n=0) at /usr/include/c++/10.2.0/bits/stl_vector.h:1112
#4  0x000055555581d4de in (anonymous namespace)::copyMissingTags (_baseFunctions=std::set with 1 element = {...}, _target=..., _declaration=0x55555645ae60)
    at solidity/libsolidity/analysis/DocStringAnalyser.cpp:69
```

#### <img src="https://avatars.githubusercontent.com/u/967816?u=e15de0869a62036529220016b1729fa1a6c18b5b&v=4" width="50">[agroce](https://github.com/agroce) commented at [2020-12-09 17:30](https://github.com/ethereum/solidity/issues/10553#issuecomment-741924929):

Oh good.  I was pretty sure if it happened on mac too it was real

#### <img src="https://avatars.githubusercontent.com/u/2388185?v=4" width="50">[bshastry](https://github.com/bshastry) commented at [2020-12-09 17:30](https://github.com/ethereum/solidity/issues/10553#issuecomment-741925063):

This looks like a duplicate of https://github.com/ethereum/solidity/issues/10433 to be fixed by https://github.com/ethereum/solidity/pull/10455

#### <img src="https://avatars.githubusercontent.com/u/967816?u=e15de0869a62036529220016b1729fa1a6c18b5b&v=4" width="50">[agroce](https://github.com/agroce) commented at [2020-12-09 20:20](https://github.com/ethereum/solidity/issues/10553#issuecomment-742025037):

Somewhat different structure/failure, right (I get a segfault for #10433 vs the vector-crash here)?  Same fix, though, I assume (it's not quite an empty tag if I understand)

#### <img src="https://avatars.githubusercontent.com/u/2388185?v=4" width="50">[bshastry](https://github.com/bshastry) commented at [2020-12-10 10:50](https://github.com/ethereum/solidity/issues/10553#issuecomment-742443498):

@agroce To be precise, I think this issue is a duplicate of https://github.com/ethereum/solidity/issues/10433#issuecomment-739850148 (please let me know if that triggers a different failure for you).

In any case, bug collisions like this are quite likely given that fuzzers are operating in similar environments. Also, sometimes different failures are triggered for the same bug that may only be known post triage.

#### <img src="https://avatars.githubusercontent.com/u/2388185?v=4" width="50">[bshastry](https://github.com/bshastry) commented at [2020-12-10 10:57](https://github.com/ethereum/solidity/issues/10553#issuecomment-742446917):

Thanks for reporting the issue @agroce 

I am going to close this issue since the fix for #10433 has now been merged. Please reopen if you believe otherwise.


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
