# [\#14170 PR](https://github.com/ethereum/solidity/pull/14170) `merged`: Fix throw of ExternalTestNotFound in external_tests.py
**Labels**: `testing :hammer:`


#### <img src="https://avatars.githubusercontent.com/u/457348?u=e02c93e6d98c1154952140a8d5af50d9d5ca59c9&v=4" width="50">[r0qs](https://github.com/r0qs) opened issue at [2023-04-28 16:01](https://github.com/ethereum/solidity/pull/14170):

Without it the exception will be raised at every run, even successful ones.




-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
