# [\#2517 Issue](https://github.com/ethereum/solidity/issues/2517) `closed`: 0.4.11 compiler doesn't throw any error but 0.4.12 throws an internal compiler error when compiling same contracts
**Labels**: `bug :bug:`


#### <img src="https://avatars.githubusercontent.com/u/26142412?u=d08221e3a98df1cbc5e65edf37e0399b5a8e4c6e&v=4" width="50">[Dexaran](https://github.com/Dexaran) opened issue at [2017-07-04 10:01](https://github.com/ethereum/solidity/issues/2517):

The source codes of contracts and error descriptions are located here: https://github.com/Dexaran/solidity/tree/master/Compiler-Errors

These contracts are compiled without errors when trying to compile them using `0.4.11+commit.68ef5810`.

There is an internal compiler error when trying to compile them using `0.4.12+commit.194ff033`.

` 0.4.12-nightly.2017.6.23+commit.793f05fa` compiles it without any errors also.
For the first time the error appears in version `0.4.12-nightly.2017.6.25+commit.29b8cdb5`.

#### <img src="https://avatars.githubusercontent.com/u/811824?v=4" width="50">[slothbag](https://github.com/slothbag) commented at [2017-07-04 10:01](https://github.com/ethereum/solidity/issues/2517#issuecomment-312849361):

I'm getting a similar issue.. contracts compiled fine in 0.4.11, in 0.4.12 I get the following error:
```
Internal compiler error during compilation:
C:\projects\solidity\libsolidity\codegen\CompilerContext.cpp(127): Throw in function void __cdecl dev::solidity::CompilerContext::addVariable(const class dev::solidity::VariableDeclaration &,unsigned int)
Dynamic exception type: class boost::exception_detail::clone_impl<struct dev::solidity::InternalCompilerError>
std::exception::what: Unknown exception
[struct dev::tag_comment * __ptr64] = Variable already present
Error performing solc 1
```

#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2017-07-04 10:01](https://github.com/ethereum/solidity/issues/2517#issuecomment-312849642):

@slothbag do you have a source code to reproduce this?

#### <img src="https://avatars.githubusercontent.com/u/811824?v=4" width="50">[slothbag](https://github.com/slothbag) commented at [2017-07-04 10:01](https://github.com/ethereum/solidity/issues/2517#issuecomment-312851856):

This appears enough to do it

```
pragma solidity ^0.4.12;
contract Test1 {
    modifier m1 {
        address a1 = msg.sender;
        _;
    }
    function f1() m1() {
    }
    function f2() m1() {   
    }
}
```

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2017-07-04 10:01](https://github.com/ethereum/solidity/issues/2517#issuecomment-312917055):

These are actually two bugs. We still need a short example that triggers the following bug:
```
Dynamic exception type: N5boost16exception_detail10clone_implIN3dev8solidity21InternalCompilerErrorEEE
std::exception::what: std::exception
[PN3dev11tag_commentE] = Unknown kind of function call .
```

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2017-07-04 10:01](https://github.com/ethereum/solidity/issues/2517#issuecomment-312923616):

"unknown kind of function call" is an error generated in the AST JSON export routine.

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2017-07-04 10:01](https://github.com/ethereum/solidity/issues/2517#issuecomment-312923771):

Ah, it might  be that this error was related to the previously incomplete compiler stack state checks, i.e. where it generated the ast json export for source that was not properly parsed.


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2022.05.23 at 03:51:38.]
