# [\#12149 Issue](https://github.com/ethereum/solidity/issues/12149) `closed`: `AssemblyException` in inline assembly when reusing the name of a recursive function
**Labels**: `bug :bug:`, `should compile without error`


#### <img src="https://avatars.githubusercontent.com/u/2388185?v=4" width="50">[bshastry](https://github.com/bshastry) opened issue at [2021-10-15 10:13](https://github.com/ethereum/solidity/issues/12149):

```
contract C {
  modifier m {
    _;
    assembly {
      function af0(i) -> a {
        if af0(0) {}
      }
    }
  }
  function f() external m m {}
}
```

throws

https://github.com/ethereum/solidity/blob/1e630fc5840bb12ad9bca2dcf1f6c534c9ba8d31/libsolidity/interface/CompilerStack.cpp#L1225

To reproduce

```
$ solc --experimental-via-ir --bin test.sol
```

#### <img src="https://avatars.githubusercontent.com/u/2388185?v=4" width="50">[bshastry](https://github.com/bshastry) commented at [2021-10-15 10:13](https://github.com/ethereum/solidity/issues/12149#issuecomment-944173529):

Note that this is not reproducible via IR optimized code i.e.,

```
$ solc --experimental-via-ir --optimize --bin test.sol
```

does not throw

#### <img src="https://avatars.githubusercontent.com/u/137030?v=4" width="50">[cameel](https://github.com/cameel) commented at [2021-10-15 10:13](https://github.com/ethereum/solidity/issues/12149#issuecomment-945200990):

Here's a simpler repro (on 0.8.9):
```solidity
contract C {
    function f() external {
        assembly {
            { function x() { x() } }
            { function x() {     } }
        }
    }
}
```

I think it's the same problem as in #12090 (or #12158), just manifesting at the inline assembly level. If you try to compile the inline assembly as a standalone yul file, you get the same error as in #12090 (an `AssemblyException` with the same message):

```yul
======= in.yul (EVM) =======

Pretty printed source:
object "object" {
    code {
        {
            function x()
            { x() }
        }
        {
            function x()
            { }
        }
    }
}

Exception while assembling: /solidity/libevmasm/Assembly.cpp(720): Throw in function const solidity::evmasm::LinkerObject& solidity::evmasm::Assembly::assemble() const
Dynamic exception type: boost::wrapexcept<solidity::evmasm::AssemblyException>
std::exception::what: Duplicate tag position.
[solidity::util::tag_comment*] = Duplicate tag position.
```

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2021-10-15 10:13](https://github.com/ethereum/solidity/issues/12149#issuecomment-946645356):

The double-invocation of the modifier is interesting! Will add it as a test.


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2022.05.23 at 03:51:38.]
